//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_V
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characteristics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Characteristics()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public double Cost { get; set; }
        public Nullable<double> list_height { get; set; }
        public Nullable<double> list_width { get; set; }
        public Nullable<double> density_paper { get; set; }
        public Nullable<int> number_of_sheets { get; set; }
        public Nullable<double> Poster_size_height_met { get; set; }
        public Nullable<double> Poster_size_width_met { get; set; }
        public int Type_Project { get; set; }
        public Nullable<double> Cardboard_density { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
