//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_V
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public int Id_Driver { get; set; }
        public string Address { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_Order_F { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Order_F Order_F { get; set; }
    }
}
